version: '3'

services:
  postgre-db:
    image: postgres:latest
    container_name: postgre-db
    user: root
    volumes:
      - postgre-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dollar_value_DB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  postgre-db: